server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 39.96.72.169:1111

management:
  endpoints:
    web:
      exposure:
        include: "*"