server:
  port: 84

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 39.96.72.169:1111
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
server-url:
  nacos-user-service: http://nacos-payment-provider